name: End-to-end tests # Nome do seu fluxo de trabalho

on:
  push: # Este fluxo de trabalho será acionado em cada push para qualquer branch
    branches:
      - main # Opcional: Especifique as branches (ex: main, develop)
  pull_request: # Opcional: Aciona o fluxo de trabalho em pull requests
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.4 # Prefira 'ubuntu-latest' para garantir a versão mais recente e evitar problemas de compatibilidade. 'ubuntu-22.04' também funciona.

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Baixa o código do seu repositório
      - name: Cypress run
        uses: cypress-io/github-action@v6 # Executa os testes Cypress
        with:
          build: npm run build # Se seu projeto requer um build antes de rodar (ex: projetos React/Vue)
          command: npm run test:e2e # Ou 'cypress run', 'yarn cypress run', 'npm test' se configurado