name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Start your application
        run: npm start & # Inicia sua aplicação em segundo plano
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm start # Ou o comando para iniciar sua aplicação
          wait-on: 'https://cac-tat.s3.eu-central-1.amazonaws.com/index.html' # Espera sua aplicação subir
