name: Cypress CI

on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
       
          
